version: "3.3"

services:
  app:
    image: elestio/pixelfed:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./storage/app-storage:/var/www/storage
      - "./.env:/var/www/.env"
    ports:
      - "172.17.0.1:8686:80"
    depends_on:
      - db
      - redis

  worker:
    image: elestio/pixelfed:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./storage/app-storage:/var/www/storage
      - "./.env:/var/www/.env"
    command: gosu www-data php artisan horizon
    depends_on:
      - db
      - redis

  db:
    image: mariadb:jammy
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./.env
    volumes:
      - "./storage/db-data:/var/lib/mysql"
    ports:
      - 172.17.0.1:4406:3306

  redis:
    image: elestio/redis:7.0
    restart: always
    env_file:
      - ./.env
    volumes:
      - "./storage/redis-data:/data"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db:db
    ports:
      - "172.17.0.1:24585:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: pixelfed
      PMA_PASSWORD: ${ADMIN_PASSWORD}
      UPLOAD_LIMIT: 500M
      MYSQL_USERNAME: pixelfed
      MYSQL_ROOT_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - db
